---
certname:
  description: "The locally unique name for this node."
server:
  description: "The puppet master server to request configurations from."
  default: dellasm
environment:
  description: "On agent nodes, the environment to request configuration in."
  default: production
ntp_server:
  description: "The server to use for synchronizing the agent's time"
  default: dellasm
